### ISSUE TITLE
After upgrading the plugin, my builds no longer succeed

### ISSUE THREAD

**Issue by motb63** [JetBrains/teamcity-aws-codedeploy-plugin#10]
Receiving the following error after updating the plugin to SNAPSHOT-201706231054.  TeamCity version 10.0.4

Step 5/32: CodeDeploy Web (AWS CodeDeploy)
    Failed to start build runner 'aws.codeDeploy'
    java.lang.NullPointerException
     at jetbrains.buildServer.runner.codedeploy.CodeDeployUtil.getReadyRevision(CodeDeployUtil.java:58)
	at jetbrains.buildServer.runner.codedeploy.ParametersValidator.validateRuntime(ParametersValidator.java:46)
	at jetbrains.buildServer.runner.codedeploy.CodeDeployRunner$1.validateParams(CodeDeployRunner.java:132)
	at jetbrains.buildServer.runner.codedeploy.CodeDeployRunner$1.runImpl(CodeDeployRunner.java:50)
	at jetbrains.buildServer.runner.codedeploy.SyncBuildProcessAdapter.waitFor(SyncBuildProcessAdapter.java:54)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:75)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:295)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:53)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:259)
	at java.lang.Thread.run(Thread.java:745)
	Step CodeDeploy Web (AWS CodeDeploy) failed with unexpected error

**Comment by assur2** [comment]
You can open the build step which fails, refresh that page, and click save. Your build should now succeed.
